local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base
  update_frequency: 1.0 #before 5.0
  publish_frequency: 2.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 2.25
  height: 2.25
  
  resolution: 0.05 #increase to for higher res 0.025
  transform_tolerance: 0.25
  cost_scaling_factor: 8
  inflation_radius: 1.2
  sim_granularity : 0.05
  angular_sim_granularity : 0.2
