TrajectoryPlannerROS:
  max_vel_x: 10
  min_vel_x: 0.004
 
  max_vel_theta: 5.8
  min_vel_theta: -2.5
 
  min_in_place_vel_theta: 9
  acc_lim_theta: 4.8
  acc_lim_x: 0.04
  acc_lim_y: 0.04
  
  max_rotational_vel: 3.9
  min_in_place_rotational_vel: -3
  
  yaw_goal_tolerance: 2
  
  holonomic_robot: false

